# -*- coding: utf-8 -*-
"""Simple_If_else_programs_python.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UmWchnPmtD5qJCVQMy6fBZUpEx3DPOnQ

1. Login program and indentation (since we don't have a database. Here we will assume that email=suxboi@gmail.com and password=12345)
"""

email=input("Enter your email: ")
password=input("Enter your password: ")

if email=="suxboi@gmail.com" and password=="12345":
    print("Login Successful")
elif email=="suxboi@gmail.com" and password!="12345":
    print("Incorrect Password")
    password=input("Enter your password again: ")
    if password=="12345":
        print("Login Successful")
    else:
        print("Login Failed")
else:
    print("Login Failed")

"""2. Find the minimum number of 3 given numbers using if else"""

a = int(input("Enter first number: "))
b = int(input("Enter second number: "))
c = int(input("Enter third number: "))

if a < b and a < c:
    print("the minimum number is",a)
elif b < a and b < c:
    print("the minimum number is:",b)
else:
    print("the minimum number is:",c)

"""3. Create a Menu  Driven Calculator"""

num1 = int(input("Enter first number: "))
num2 = int(input("Enter second number: "))

operator = input("Enter operator(+,-,*,/,%): ")

if operator == "+":
    print('Addition of',num1,'and',num2,'is',num1 + num2)
elif operator == "-":
    print('Subtraction of',num1,'and',num2,'is',num1 - num2)
elif operator == "*":
    print('Multiplication of',num1,'and',num2,'is',num1 * num2)
elif operator == "/":
    print('Division of',num1,'and',num2,'is',num1 / num2)
elif operator == "%":
    print('Modulus of',num1,'and',num2,'is',num1 % num2)
else:
  print("YOU ARE NOT USING A VALIID OPERATOR")

"""4. Find the sum of 3 digit number entered by the user. Using only Operators."""

number = int(input("Enter a three digit number: "))

a = number % 10
number = number // 10
b = number % 10
number = number // 10
c = number % 10

print("The sum of the digits is:",a+b+c)

